openapi: 3.0.3
info:
  title: Accounts Microservice
  termsOfService: http://swagger.io/terms/
  contact:
    email: anacarenasr@sgmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api/v1
    description: Servidor de desarrollo
tags:
  - name: account
    description: Operaciones relacionadas con cuentas
paths:
  /account:
    get:
      tags:
        - account
      summary: Obtener todas las cuentas
      responses:
        '200':
          description: Lista de todas las cuentas
          content:
            application/json:
              example:
                - id: 1
                  customerId: 1
                  typeAccount: savings
                  descriptTypeAccount: Savings Account
                  amount: 5000.00
                  maintance: 10.00
                  transaction: 0.00
                  operationDay: Monday
                  dateAccount: '2022-01-01'
                  numberAccount: SA-123456
                  typeCustomer: personal
                - id: 2
                  customerId: 2
                  typeAccount: current
                  descriptTypeAccount: Current Account
                  amount: 10000.00
                  maintance: 20.00
                  transaction: 0.00
                  operationDay: Tuesday
                  dateAccount: '2022-01-02'
                  numberAccount: CA-987654
                  typeCustomer: business
    post:
      tags:
        - account
      summary: Crear una nueva cuenta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '201':
          description: Cuenta creada exitosamente
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              example:
                message: Error de validación en la solicitud
  /account/{id}:
    get:
      tags:
        - account
      summary: Obtener una cuenta por ID
      parameters:
        - name: id
          in: path
          description: ID único de la cuenta
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Detalles de la cuenta
          content:
            application/json:
              example:
                id: 1
                customerId: 1
                typeAccount: savings
                descriptTypeAccount: Savings Account
                amount: 5000.00
                maintance: 10.00
                transaction: 0.00
                operationDay: Monday
                dateAccount: '2022-01-01'
                numberAccount: SA-123456
                typeCustomer: personal
        '404':
          description: Cuenta no encontrada
    put:
      tags:
        - account
      summary: Actualizar una cuenta existente
      parameters:
        - name: id
          in: path
          description: ID único de la cuenta
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Cuenta actualizada exitosamente
        '400':
          description: Solicitud incorrecta
          content:
            application/json:
              example:
                message: Error de validación en la solicitud
        '404':
          description: Cuenta no encontrada
    delete:
      tags:
        - account
      summary: Eliminar una cuenta
      parameters:
        - name: id
          in: path
          description: ID único de la cuenta
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Cuenta eliminada exitosamente
        '404':
          description: Cuenta no encontrada
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID único de la cuenta
        customerId:
          type: integer
          format: int64
          description: ID del cliente asociado a la cuenta.
        typeAccount:
          type: string
          description: Tipo de cuenta.
        descriptTypeAccount:
          type: string
          description: Descripción del tipo de cuenta.
        amount:
          type: number
          format: float
          description: Monto disponible en la cuenta.
        maintance:
          type: number
          format: float
          description: Monto de mantenimiento de la cuenta.
        transaction:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
          description: Lista de transacciones asociadas a la cuenta.
        operationDay:
          type: string
          format: date
          description: Día de operación de la cuenta.
        dateAccount:
          type: string
          format: date
          description: Fecha de creación de la cuenta.
        numberAccount:
          type: string
          description: Número de cuenta.
        typeCustomer:
          type: string
          enum: [ individual, business ]
          description: Tipo de cliente asociado a la cuenta.

      required:
        - customerId
        - typeAccount
        - descriptTypeAccount
        - amount
        - maintance
        - transaction
        - operationDay
        - dateAccount
        - numberAccount
        - typeCustomer

    Transaction:
      type: object
      properties:
        productType:
          type: string
          description: Tipo de producto asociado a la transacción.
        productId:
          type: integer
          format: int64
          description: ID del producto asociado a la transacción.
        customerId:
          type: integer
          format: int64
          description: ID del cliente asociado a la transacción.
        transactionType:
          type: string
          description: Tipo de transacción.
        amount:
          type: number
          format: float
          description: Monto de la transacción.
        transactionDate:
          type: string
          format: date
          description: Fecha de la transacción.
        customerType:
          type: string
          enum: [ individual, business ]
          description: Tipo de cliente asociado a la transacción.
        balance:
          type: number
          format: float
          description: Saldo después de la transacción.
      required:
        - productType
        - productId
        - customerId
        - transactionType
        - amount
        - transactionDate
        - customerType
        - balance