/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.nttdata.ms_accounts.api;

import com.nttdata.ms_accounts.model.Account;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-01-23T08:30:55.149919600-05:00[America/Bogota]")
@Tag(name = "account", description = "Operaciones relacionadas con cuentas")
public interface AccountApi {

    default AccountApiDelegate getDelegate() {
        return new AccountApiDelegate() {};
    }

    /**
     * GET /account : Obtener todas las cuentas
     *
     * @return Lista de todas las cuentas (status code 200)
     */
    @Operation(
        operationId = "accountGet",
        summary = "Obtener todas las cuentas",
        tags = { "account" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de todas las cuentas")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/account",
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Void>> accountGet(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getDelegate().accountGet(exchange);
    }


    /**
     * DELETE /account/{id} : Eliminar una cuenta
     *
     * @param id ID único de la cuenta (required)
     * @return Cuenta eliminada exitosamente (status code 204)
     *         or Cuenta no encontrada (status code 404)
     */
    @Operation(
        operationId = "accountIdDelete",
        summary = "Eliminar una cuenta",
        tags = { "account" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Cuenta eliminada exitosamente"),
            @ApiResponse(responseCode = "404", description = "Cuenta no encontrada")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/account/{id}"
    )
    default Mono<ResponseEntity<Void>> accountIdDelete(
        @Parameter(name = "id", description = "ID único de la cuenta", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getDelegate().accountIdDelete(id, exchange);
    }


    /**
     * GET /account/{id} : Obtener una cuenta por ID
     *
     * @param id ID único de la cuenta (required)
     * @return Detalles de la cuenta (status code 200)
     *         or Cuenta no encontrada (status code 404)
     */
    @Operation(
        operationId = "accountIdGet",
        summary = "Obtener una cuenta por ID",
        tags = { "account" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Detalles de la cuenta"),
            @ApiResponse(responseCode = "404", description = "Cuenta no encontrada")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/account/{id}",
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Void>> accountIdGet(
        @Parameter(name = "id", description = "ID único de la cuenta", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getDelegate().accountIdGet(id, exchange);
    }


    /**
     * PUT /account/{id} : Actualizar una cuenta existente
     *
     * @param id ID único de la cuenta (required)
     * @param account  (required)
     * @return Cuenta actualizada exitosamente (status code 200)
     *         or Solicitud incorrecta (status code 400)
     *         or Cuenta no encontrada (status code 404)
     */
    @Operation(
        operationId = "accountIdPut",
        summary = "Actualizar una cuenta existente",
        tags = { "account" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Cuenta actualizada exitosamente"),
            @ApiResponse(responseCode = "400", description = "Solicitud incorrecta"),
            @ApiResponse(responseCode = "404", description = "Cuenta no encontrada")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/account/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<Void>> accountIdPut(
        @Parameter(name = "id", description = "ID único de la cuenta", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "Account", description = "", required = true) @Valid @RequestBody Mono<Account> account,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getDelegate().accountIdPut(id, account, exchange);
    }


    /**
     * POST /account : Crear una nueva cuenta
     *
     * @param account  (required)
     * @return Cuenta creada exitosamente (status code 201)
     *         or Solicitud incorrecta (status code 400)
     */
    @Operation(
        operationId = "accountPost",
        summary = "Crear una nueva cuenta",
        tags = { "account" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Cuenta creada exitosamente"),
            @ApiResponse(responseCode = "400", description = "Solicitud incorrecta")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/account",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<Void>> accountPost(
        @Parameter(name = "Account", description = "", required = true) @Valid @RequestBody Mono<Account> account,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        return getDelegate().accountPost(account, exchange);
    }

}
